### ISSUE TITLE
This is not an issue. More like a help.

### ISSUE THREAD

**Issue by ramanareddy438** [hasanozgan/apache-oltu-oauth2-provider-demo#2]
Hi hasanozgan,

I am trying to run this project in my eclipse. I did everything. I am running this application in tomcat. From where i can start in this project?. Is it Registration? I tried to send post request to /registration  url, but it is saying     
{
"error": "invalid_request",
   "error_description": "Missing [type] parameter value"
}
Any suggestion would be greatly helpful.

Regards
Ramana Reddy

**Comment by hasanozgan** [comment]
I have added README file. 

Type should be pull or push. http://svn.apache.org/repos/asf/oltu/site/amber-oauth2-parent/amber-oauth2-dynamicreg-common/apidocs/org/apache/amber/oauth2/ext/dynamicreg/common/OAuthRegistration.Type.html
