### ISSUE TITLE
after check out i am getting lot of building issues.. Could you please let me know is this is update

### ISSUE THREAD

**Issue by early123** [hasanozgan/apache-oltu-oauth2-provider-demo#3]
after check out i am getting lot of building issues.. Could you please let me know is this is update

**Comment by damn-good** [comment]
Me too. I can't build this. I get this error...


zephyr@zephyr-HP-250-G3-Notebook-PC:~/apache-oltu-oauth2-provider-demo-master$ mvn clean install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building api-web Maven Webapp 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://download.java.net/maven/2/org/apache/oltu/oltu-oauth2-common/0.31-SNAPSHOT/maven-metadata.xml
Downloading: http://download.java.net/maven/2/org/apache/oltu/oltu-oauth2-common/0.31-SNAPSHOT/oltu-oauth2-common-0.31-SNAPSHOT.pom
[WARNING] The POM for org.apache.oltu:oltu-oauth2-common:jar:0.31-SNAPSHOT is missing, no dependency information available
Downloading: http://download.java.net/maven/2/org/apache/oltu/oltu-oauth2-client/0.31-SNAPSHOT/maven-metadata.xml
Downloading: http://download.java.net/maven/2/org/apache/oltu/oltu-oauth2-client/0.31-SNAPSHOT/oltu-oauth2-client-0.31-SNAPSHOT.pom
[WARNING] The POM for org.apache.oltu:oltu-oauth2-client:jar:0.31-SNAPSHOT is missing, no dependency information available
Downloading: http://download.java.net/maven/2/org/apache/oltu/oltu-oauth2-authzserver/0.31-SNAPSHOT/maven-metadata.xml


... and it keeps going in that way oltu dependencies can't be found. I'm I building it some wrong way?

**Comment by hasanozgan** [comment]
fixed
