### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by eniniz** [hasanozgan/apache-oltu-oauth2-provider-demo#5]
Hi,
thank you for the demo, it doesn't contained a lot of code, and I can guess the use of each class and  method, but it will be nice if the code were documented, so that we can confirm our guesses :)

**Comment by jeneive** [comment]
Hi, 

I am trying ALTU first time. I have added the files and jars from this demo project. Tomcat up, but getting error message when I am calling URL "http://localhost:9090/apld/register" with POST. 

Is there any setup before starting tomcat ?

**Comment by nilathj** [comment]
You will need to POST to url /register with a paylod of 
{ 
  type: "pull", 
  client_name:"test-app", 
  client_url:"localhost:8080", 
  client_description:"example app", 
  redirect_url:"localhost:8080" 
}

Then you will get a response 200, with a payload of 
{
  "client_secret": "someclientsecret",
  "issued_at": "0123456789",
  "expires_in": 987654321,
  "client_id": "someclientid"
}

**Comment by jeneive** [comment]
Thanks nilathj..  It was a jar issue. Fixed

**Comment by nilathj** [comment]
I've created a pull request with more documentation in the readme.md file and a postman collection to try out the endpoints.

**Comment by eniniz** [comment]
thank you
